server:
  port: 8301
spring:
  #  SpringCloud Config
  #  application:
  #    name: borrowservice
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://127.0.0.1:3306/springcloud
  #    username: testdb
  #    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
        #        ephemeral: false
        cluster-name: china
    loadbalancer:
      nacos:
        enabled: true
feign:
  oauth2:
    #开启Oauth支持，这样就会在请求头中携带Token了
    enabled: true
    #同时开启负载均衡支持
    load-balanced: true
security:
  oauth2:
    client:
      client-id: web
      client-secret: 654321
    resource:
      #因为资源服务器得验证你的Token是否有访问此资源的权限以及用户信息，所以只需要一个验证地址
      token-info-uri: http://localhost:8501/sso/oauth/check_token

test:
  txt: abcd
