server:
  port: 8888
spring:
  banner:
    charset: utf-8
    location: classpath:banner.txt
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  messages:
    basename: message/validation
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        max-wait: -1ms
    connect-timeout: 30000ms

knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Java 全栈]()
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models