spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_web?useSSL=false&serverTimezone=UTC
    username: testdb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456