server:
  port: 8080

spring:
  security:
    user:
      name: testuser
      password: 123456
  datasource:
    schema: classpath:script/database/h2/schema.sql
    data: classpath:script/database/h2/data.sql
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
