server:
  port: 8101
spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud
    username: testdb
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
        cluster-name: china
    loadbalancer:
      nacos:
        enabled: true
security:
  oauth2:
    client:
      client-id: web
      client-secret: 654321
    resource:
      #因为资源服务器得验证你的Token是否有访问此资源的权限以及用户信息，所以只需要一个验证地址
      token-info-uri: http://localhost:8501/sso/oauth/check_token
