server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb
    schema: classpath:script/database/h2/schema.sql
    data: classpath:script/database/h2/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  profiles:
    active:
      - prod
---
spring:
  profiles: dev
logging:
  level:
    taco: debug
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: tacouser
    password: tacopassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:script/database/mysql/schema_mysql.sql
    data: classpath:script/database/mysql/data_mysql.sql
logging:
  level:
    tacos: warn